DROP DATABASE IF EXISTS InstituteDB;
CREATE DATABASE IF NOT EXISTS InstituteDB;
SHOW DATABASES;
USE InstituteDB;

DROP TABLE IF EXISTS Employee;
CREATE TABLE IF NOT EXISTS Employee(
   Employee_Id VARCHAR(50),
   Employee_Name VARCHAR(200) NOT NULL DEFAULT "Unknown",
   Gender VARCHAR(50),
   Mobile_Num INT(15),
   Email VARCHAR(100),
   Address VARCHAR (200),
   Nic VARCHAR(30),
   Reg_Date DATE,
   Job_Title VARCHAR(50) NOT NULL DEFAULT "Unknown",
   CONSTRAINT PRIMARY KEY (Employee_Id)

    );
SHOW TABLES ;
DESCRIBE Employee;

DROP TABLE IF EXISTS Salary;
CREATE TABLE IF NOT EXISTS Salary(
    Salary_Id VARCHAR(50),
    Employee_Id VARCHAR(50) NOT NULL DEFAULT "Unknown",
    Salary_Cost DOUBLE NOT NULL,
    R_year VARCHAR(50),
    R_Month VARCHAR(50),
    Date DATE,
    Time VARCHAR(50) ,
    Stutus VARCHAR(50),
    CONSTRAINT PRIMARY KEY (Salary_Id),
    CONSTRAINT FOREIGN KEY (Employee_Id) REFERENCES Employee(Employee_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE Salary;

DROP TABLE IF EXISTS Students;
CREATE TABLE IF NOT EXISTS Students(
    Stud_Id VARCHAR(50),
    Stud_Name VARCHAR(100) NOT NULL DEFAULT "Unknown",
    Mobile_Num INT(15),
    Email VARCHAR(50),
    Birthday VARCHAR(50),
    Address VARCHAR (150),
    Gender VARCHAR(50),
    Trustee_Name VARCHAR(100) NOT NULL DEFAULT "Unknown",
    Nic VARCHAR(20)DEFAULT "No NIC",
    Reg_Date DATE NOT NULL,
    CONSTRAINT PRIMARY KEY (Stud_Id)
    );
SHOW TABLES;
DESCRIBE Students;

DROP TABLE IF EXISTS Teachers;
CREATE TABLE IF NOT EXISTS Teachers(
    Teacher_Id VARCHAR (10), 
    Teacher_Name VARCHAR (50) NOT NULL NOT NULL DEFAULT "Unknown",
    Mobile_Num INT (13),
    Email VARCHAR (20),
    Birthday VARCHAR(20) ,
    School_Name VARCHAR (40),
    Nic VARCHAR (25)DEFAULT "No NIC",
    Address VARCHAR (60),
    Reg_Date DATE NOT NULL,
    CONSTRAINT PRIMARY KEY (Teacher_Id)
    );
SHOW TABLES ;
DESCRIBE Teachers;

DROP TABLE IF EXISTS Classes;
CREATE TABLE IF NOT EXISTS Classes (
    Class_Id VARCHAR (10),
    Teacher_Id VARCHAR (10) NOT NULL DEFAULT "Unknown",
    Subject_Name VARCHAR (50) NOT NULL DEFAULT "Unknown",
    Class_Fee DOUBLE  NOT NULL,
    Gread VARCHAR (7) NOT NULL DEFAULT "Unknown",
    Title VARCHAR (70), 
    Class_Type VARCHAR (15), 
    Short_Desc VARCHAR (100) ,
    Reg_Date Date,
    CONSTRAINT PRIMARY KEY (Class_Id),
    CONSTRAINT FOREIGN KEY (Teacher_Id) REFERENCES Teachers(Teacher_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE Classes;

DROP TABLE IF EXISTS StudentClass;
CREATE TABLE IF NOT EXISTS StudentClass (
    Stud_Id VARCHAR(10),
    Class_Id VARCHAR(10),
    CONSTRAINT PRIMARY KEY (Stud_Id,Class_Id),
    CONSTRAINT FOREIGN KEY (Stud_Id) REFERENCES Students(Stud_Id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (Class_Id) REFERENCES Classes(Class_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE StudentClass;

DROP TABLE IF EXISTS Payment;
CREATE TABLE IF NOT EXISTS Payment (
    Payment_Code VARCHAR (50), 
    Teacher_Id VARCHAR (50) NOT NULL,
    Class_Id VARCHAR (50) NOT NULL,
    Total_Cost DOUBLE NOT NULL,
    R_Year VARCHAR(50) NOT NULL,
    R_Month VARCHAR (50)NOT NULL,
    pay_Date DATE NOT NULL,
    pay_Time VARCHAR(50) NOT NULL DEFAULT "00.00.00",
    Stutus VARCHAR(50) NOT NULL DEFAULT "Unknown",
    CONSTRAINT PRIMARY KEY (Payment_Code),
    CONSTRAINT FOREIGN KEY (Teacher_Id) REFERENCES Teachers(Teacher_Id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (Class_Id) REFERENCES Classes(Class_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE Payment;


DROP TABLE IF EXISTS Shedule;
CREATE TABLE IF NOT EXISTS Shedule (
    Class_Id VARCHAR(10) NOT NULL,
    Shedule_Type VARCHAR(10) NOT NULL DEFAULT "Unknown",
    Date VARCHAR(20),
    Day VARCHAR(15),
    Time VARCHAR(10) NOT NULL DEFAULT "00.00.00",
    CONSTRAINT FOREIGN KEY (Class_Id) REFERENCES Classes(Class_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE Shedule;


DROP TABLE IF EXISTS Attendence;
CREATE TABLE IF NOT EXISTS Attendence (
    Class_Id VARCHAR(50) NOT NULL,
    Stud_Id VARCHAR(50),
    Stud_Name VARCHAR(100), 
    Date DATE,
    Time VARCHAR(50) NOT NULL DEFAULT "00.00.00",
    Stutus VARCHAR(50),
    CONSTRAINT FOREIGN KEY (Class_Id) REFERENCES Classes(Class_Id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (Stud_Id) REFERENCES Students(Stud_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE Attendence;


DROP TABLE IF EXISTS Money;
CREATE TABLE IF NOT EXISTS Money (
    Class_Id VARCHAR(50) NOT NULL,
    Relevent_Year VARCHAR(50) ,
    Relevent_Month VARCHAR(50),
    Class_Profit DOUBLE NOT NULL,
    Institute_Profit DOUBLE NOT NULL,
    CONSTRAINT FOREIGN KEY (Class_Id) REFERENCES Classes(Class_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE Money;


DROP TABLE IF EXISTS ClassFee;
CREATE TABLE IF NOT EXISTS ClassFee (
    Fee_Id VARCHAR(50),
    Stud_Id VARCHAR(50) NOT NULL,
    Class_Id VARCHAR(50) NOT NULL,
    Fee_Cost DOUBLE NOT NULL,
    Pay_Date DATE NOT NULL,
    Pay_Time VARCHAR(50)DEFAULT "00.00.00",
    Relevent_Year VARCHAR(50) NOT NULL DEFAULT "Unknown",
    Relevent_Month VARCHAR(50) NOT NULL DEFAULT "Unknown",
    Stutus VARCHAR(50),
    CONSTRAINT PRIMARY KEY (Fee_Id),
    CONSTRAINT FOREIGN KEY (Stud_Id) REFERENCES Students(Stud_Id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (Class_Id) REFERENCES Classes(Class_Id) ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES ;
DESCRIBE ClassFee;



DROP TABLE IF EXISTS User;
CREATE TABLE IF NOT EXISTS User (
    User_Id VARCHAR(10),
    User_Name VARCHAR(20) NOT NULL DEFAULT "Unknown",
    Nic VARCHAR(15)NOT NULL DEFAULT "Unknown",
    Email VARCHAR(20),
    Mobile_Num VARCHAR(18),
    Address VARCHAR(50),
    Password VARCHAR(20),
    CONSTRAINT PRIMARY KEY (User_Id)
    );
SHOW TABLES ;
DESCRIBE User;



